spring.datasource.url=jdbc:postgresql://localhost:5432/hmis
spring.datasource.username=postgres
spring.datasource.password=sumasoft123

#cors origin path
origin.url=http://localhost:4200

#Log path specific properties
log.path=EchoTNT_logs

server.port=8081

## Email configuration
#from.email.username =test_email1@sumasoft.net
#from.email.password =TeamWFEtest1@1234
#to.email.username =
#
##Error File Path
#error.file.path=D://Echo_TNT/
